

services:
  vectra-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vectra_frontend_dev
    ports:
      - "3000:3000" # Web Server
    volumes:
      - .:/app # Mount source code
    working_dir: /app
    environment:
      - CHROME_EXECUTABLE=/usr/bin/google-chrome
    command: flutter run -d web-server --web-port 3000 --web-hostname 0.0.0.0
