name: vectra
description: Premium ride-sharing app with cinematic UI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.0
  
  # UI/FX
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  
  # Networking
  dio: ^5.4.0
  
  # Navigation
  go_router: ^13.0.0
  
  # Storage
  flutter_secure_storage: ^9.0.0
  
  # Utils
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  google_maps_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/future_car.png
