services:
  db:
    image: postgis/postgis:16-3.4
    container_name: vectra_db
    environment:
      POSTGRES_USER: vectra
      POSTGRES_PASSWORD: vectra_pass
      POSTGRES_DB: vectra_db
    ports:
      - "5432:5432"
    volumes:
      - vectra_db_data:/var/lib/postgresql/data
    networks:
      - vectra-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U vectra -d vectra_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: vectra_redis
    ports:
      - "6379:6379"
    networks:
      - vectra-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vectra_backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - vectra-network

volumes:
  vectra_db_data:


networks:
  vectra-network:


