services:
  db:
    image: postgis/postgis:16-3.4
    container_name: vectra_db
    environment:
      POSTGRES_USER: vectra
      POSTGRES_PASSWORD: vectra_pass
      POSTGRES_DB: vectra_db
    ports:
      - "5433:5432"
    volumes:
      - vectra_db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: vectra_redis
    ports:
      - "6379:6379"

volumes:
  vectra_db_data:
